env = Environment()

env['APP_TARGET'] = 'Capture1394App'
env['APP_SOURCES'] = ['Capture1394App.cpp']
env['DEBUG'] = 1

# Cinder-Capture1394
env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')

